{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rulebricks-chart.app.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rulebricks-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-hpa
  annotations:
    description: "Automatically scales the Next.js UI based on resource usage"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rulebricks-chart.app.fullname" . }}
  minReplicas: {{ .Values.app.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas | default 6 }}
  {{- with .Values.app.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait 1 minute before scaling up
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Add at most 1 pod per minute
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Remove at most 1 pod per minute
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage | default 50 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
{{- end }}
