{{- if and .Values.hps .Values.hps.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rulebricks-chart.hps.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rulebricks-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: hps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rulebricks-chart.hps.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
