apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rulebricks-chart.redis.pvc" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rulebricks-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | default "1Gi" }}
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
