apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rulebricks-chart.registrySecretName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "rulebricks-chart.imagePullSecret" . }}
